apiVersion: v1
kind: Service
metadata:
  name: {{ include "exercises.fullname" . }}-postgres
  labels:
    {{- include "exercises.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: pg
