apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.fullname" . }}-elasticsearch
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: elasticsearch
