apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exercises.fullname" . }}-postgres
  labels:
    {{- include "exercises.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  DB_PASSWORD: {{ .Values.postgres.auth.password | quote }}
